# serverless.yml

service: my-express-application

custom: ${file(./custom.yml):custom}

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  profile: ${self:custom.myProfile.${self:custom.myStage}}
  environment:
    ENVIRON: ${self:custom.myStage}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'