# serverless.yml

service: my-express-application

custom:
  myStage: ${opt:stage, self:provider.stage}
  myProfile:
    production: production
    qa2: default
  myEnvironment:
    MESSAGE:
      production: "This is production environment"
      qa2: "This is qa2 environment"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  profile: ${self:custom.myProfile.${self:custom.myStage}}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'